#if !canImport(ObjectiveC)
import XCTest

extension MarkdownExtensionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MarkdownExtensionTests = [
        ("testAutolink", testAutolink),
        ("testEmailFriendly", testEmailFriendly),
        ("testFencedCode", testFencedCode),
        ("testInsertion", testInsertion),
        ("testLaxSpacing", testLaxSpacing),
        ("testNoIntraEmphasis", testNoIntraEmphasis),
        ("testSpaceHeaders", testSpaceHeaders),
        ("testStrikethrough", testStrikethrough),
        ("testSuperscript", testSuperscript),
        ("testTables", testTables),
    ]
}

extension PerfectMarkdownTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PerfectMarkdownTests = [
        ("testCodes", testCodes),
        ("testInlineCode", testInlineCode),
        ("testLink", testLink),
        ("testList", testList),
        ("testNumbers", testNumbers),
        ("testTable", testTable),
        ("testTitle", testTitle),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MarkdownExtensionTests.__allTests__MarkdownExtensionTests),
        testCase(PerfectMarkdownTests.__allTests__PerfectMarkdownTests),
    ]
}
#endif
