#if !canImport(ObjectiveC)
import XCTest

extension HTMLRenderOptionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HTMLRenderOptionsTests = [
        ("testCreateOutline", testCreateOutline),
        ("testEscapeHTML", testEscapeHTML),
        ("testHardWrap", testHardWrap),
        ("testSafeLinks", testSafeLinks),
        ("testSkipHTML", testSkipHTML),
        ("testSkipImages", testSkipImages),
        ("testSkipLinks", testSkipLinks),
        ("testSkipStyle", testSkipStyle),
        ("testTableOfContents", testTableOfContents),
        ("testUseXHTML", testUseXHTML),
    ]
}

extension MarkdownExtensionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MarkdownExtensionTests = [
        ("testAutolink", testAutolink),
        ("testEmailFriendly", testEmailFriendly),
        ("testFencedCode", testFencedCode),
        ("testInsertion", testInsertion),
        ("testLaxSpacing", testLaxSpacing),
        ("testNoIntraEmphasis", testNoIntraEmphasis),
        ("testSpaceHeaders", testSpaceHeaders),
        ("testStrikethrough", testStrikethrough),
        ("testSuperscript", testSuperscript),
        ("testTables", testTables),
    ]
}

extension PerfectMarkdownTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PerfectMarkdownTests = [
        ("testCodes", testCodes),
        ("testInlineCode", testInlineCode),
        ("testLink", testLink),
        ("testList", testList),
        ("testNumbers", testNumbers),
        ("testTable", testTable),
        ("testTitle", testTitle),
        ("testXHTMLRendering", testXHTMLRendering),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HTMLRenderOptionsTests.__allTests__HTMLRenderOptionsTests),
        testCase(MarkdownExtensionTests.__allTests__MarkdownExtensionTests),
        testCase(PerfectMarkdownTests.__allTests__PerfectMarkdownTests),
    ]
}
#endif
